version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/coclip-frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/services/auth-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/services/engine"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
